# Generated by Django 4.2.2 on 2023-06-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=2000)),
                ('tel', models.CharField(max_length=2000)),
                ('lokatsya', models.TextField()),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=2000)),
                ('familya', models.CharField(max_length=2000)),
                ('data', models.DateField()),
                ('img', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=2000)),
                ('manzil', models.CharField(max_length=20000)),
                ('uzi_haqida', models.TextField()),
                ('tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_name', models.CharField(max_length=200)),
                ('services_text', models.TextField()),
                ('services_img', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': 'services',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_name', models.CharField(max_length=200)),
                ('skills', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Skills',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics', models.TextField()),
                ('clients', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('monthly_experience', models.IntegerField()),
            ],
        ),
    ]
